version: '3.8' #Verison de docker-compose
services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
        - .:/var/www/html
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=servicioSocial
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=12345
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
